CREATE DATABSE EJERCICIO1; 
USE EJERCICIO1; 
CREATE TABLE departamentos(
dept no TINYINT(2) NOT NULL, 
dnombre VARCHAR(159, 
loc VARCHAR(15)
); 

INSERT INTO departamentos VALUES (10, 'CONTABILIDAD', 'SEVILLA'); 
INSERT INTO departamentos VALUES (20, 'INVESTIGACION', 'MADRID'); 
INSERT INTO departamentos VALUES (30, 'VENTAS, 'BARCELONA'); 
INSERT INTO departamentos VALUES (40, 'PRODUCCION', 'BILBAO'); 
DESCRIBE DEPARTAMENTOS; 
